### ISSUE TITLE
Move repo to Dracula's official org

### ISSUE THREAD

**Issue by zenorocha** [yl0g0ly/dracula-ui#5]
Hello @ichi0g0y!

I'm the creator of Dracula color scheme. I was searching for themes created by the community and I found yours. Good job by the way!

I was wondering if you are interested in transferring this repository to the official organization (https://github.com/dracula). You'll continue maintaining this project, the only difference is that we can make it more visible and include it on the site (https://draculatheme.com).

What do you think?

**Comment by ichi0g0y** [comment]
Hello @zenorocha.

Previously, I tried to move the repository.
There is that conversation in #3.
Github 's repository transfer is fine, but I do not know how to transfer APM.

Once you know the procedure, I'd like to join quickly :)

**Comment by zenorocha** [comment]
Awesome!

I sent you an invitation to join the organization, once you accept that we can continue moving forward.

**Comment by ichi0g0y** [comment]
Thank you, i am joined now.

**Comment by zenorocha** [comment]
Ok, now go to https://github.com/ichi0g0y/dracula-ui/settings and select `Transfer`.

Then, apply this template (https://github.com/dracula/template) which includes `README`, `LICENSE`, and `.github`.

**Comment by zenorocha** [comment]
You can also rename the repo to `atom-ui`.

**Comment by ichi0g0y** [comment]
Github's transfer is complete.
What should I do with APM?

**Comment by ichi0g0y** [comment]
Remove `dracura-ui` from my APM repository for now and Would you like to register to APM from Dracula team?

**Comment by zenorocha** [comment]
I think Atom's registry just uses the GitHub organization, so you can still publish it with your user in the same way.

**Comment by zenorocha** [comment]
Try releasing a new version to see what happens.

**Comment by ichi0g0y** [comment]
i'm tried `apm publish minor`, how about it?

**Comment by JimmyMultani** [comment]
Hey @ichi0g0y, it's because the theme `name` is set to `atom-ui` in the `package.json` file. You might need to rename it back to `dracula-ui`.

**Comment by ichi0g0y** [comment]
Hi @JimmyMultani, i tried `apm --rename dracula-ui`. but an error occurred -> `Creating new version failed: A package by that name already exists`. i deleted old repository `dracula-ui`. but it seems that it still exists.

**Comment by JimmyMultani** [comment]
Hey @ichi0g0y, I moved it over for you. :)

**Comment by ichi0g0y** [comment]
nice work! thank you!

**Comment by alexrussell** [comment]
Close issue?
