### ISSUE TITLE
Git file modified colour should be yellow/orange not purple?

### ISSUE THREAD

**Issue by alexrussell** [yl0g0ly/dracula-ui#9]
Looks like the theme has a bit of a convoluted way of working out the git-file-modified colour (presumably due to being based on Atom's own one-dark UI theme) but following the trail it looks like the `status-modified` class for the tabs and tree view uses the `@git-color-modified` variable, which in turn uses the `@text-color-modified` variable, which in turn uses the `@text-color-warning` variable which is set to Dracula's purple colour (`@ui-purple`).

I think this `@text-color-warning` variable should be changed to Dracula's yellow or orange colour (`@ui-yellow` or `@ui-orange `) - people are much more used to yellow or orange for warnings and modification statuses than purple.

**Comment by shahi645** [comment]
🌚

**Comment by zenorocha** [comment]
Should be fixed now with #10
